title: Multi-domain GitHub Pages
description: A multi-domain GitHub Pages repository
baseurl: "" # the subpath of your site
url: "https://magik.works" # the default hostname

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - blog.md
  - _layouts/post.html
  - _posts

# Theme settings
sass:
  style: compressed
  sass_dir: _sass

# Domain-specific configurations
domains:
  - name: magik.works
    domain: magik.works
    directory: magik.works
  - name: debert.xyz
    domain: debert.xyz
    directory: debert.xyz
  - name: txxt.is
    domain: txxt.is
    directory: txxt.is
